### ISSUE TITLE
Feature Request: `update` command

### ISSUE THREAD

**Issue by TrueWinter** [NdT3Development/DiscordBot#18]
When used, this command will get the latest commit from GitHub and restart the bot. After the bot has restarted, the user will have to run a command such as `update guildSettings` to update the per guild settings if there are any new configuration options for these.

**Comment by TrueWinter** [comment]
This could be hard to do for cases when an update has a breaking change (most common example of this would be a new guild configuration option which will require the new option to be added to all existing server settings).

**Comment by ChineseMarc** [comment]
.

**Comment by TrueWinter** [comment]
Not sure why you want me to close this...

**Comment by ChineseMarc** [comment]
Hmmm looks like someone used my account..... Sorry 😐

**Comment by ethamitc** [comment]
Just gonna put my foot in here, what you're trying to do is theoretically impossible, as you **cannot** overwrite code that's currently being run. It will return as access denied.

**Comment by TrueWinter** [comment]
I have on multiple occasions been able to successfully edit code in the commands and then run a reload command to load the changes. So with this system in place, I don't see how this could be impossible.

**Comment by ChineseMarc** [comment]
Maybe make startup scripts for windows and linux and have option to update and if there is breaking change just say in console 
```bash
There's breaking change.... 
You need to update code yourself

**Comment by ethamitc** [comment]
@NdT3Development Yes, you can run an update command. But that's because the commands are cached. You can't make changes to always-active files such as the main file.

**Comment by TrueWinter** [comment]
True, probably going to do something like @ChineseMarc said with a script to update the files and the database.

**Comment by ethamitc** [comment]
@NdT3Development That could work. You could also have a different file named `start.js` that can be reloaded which stops running index.js

**Comment by audiodk** [comment]
I don't know if this would help or not but maybe you could do a update script sort like these guys did.  Granted this on is for C# but might give you some ideas.

https://github.com/NaamloosDT/ModCore

**Comment by TrueWinter** [comment]
Won't be needing this open anymore.
