### ISSUE TITLE
Bot Database

### ISSUE THREAD

**Issue by TrueWinter** [NdT3Development/DiscordBot#19]
Change the bot database to use something like SQLite.
This will allow for much better data storage, such as support for better warnings and being able to store cases in a database which will help with issues seen recently that have caused the new case number system to not work as intended.
(That's going to push the next version back a bit)

**Comment by TrueWinter** [comment]
Database to use has been decided: Postgres.

**Comment by TrueWinter** [comment]
Using an actual database may be an issue when it comes to testing as the server that I use for testing may not be able to handle another database running with everything else running on it already. I am unsure about whether to actually implement this or to keep with the current system.

**Comment by ChineseMarc** [comment]
I can rewrite bot to mongodb (moongose) if you want

**Comment by TrueWinter** [comment]
Thanks but after thinking about this, I have decided to leave the current data storage and not change to another database.
