### ISSUE TITLE
Command doesn't run if no mod-log channel exists

### ISSUE THREAD

**Issue by TrueWinter** [NdT3Development/DiscordBot#2]
If commands are run in a server where there is no mod log channel, the commands do not get executed, instead get console error.

**Comment by TrueWinter** [comment]
Should be an easy fix now that I think of it

**Comment by TrueWinter** [comment]
Is this really an issue? This is supposed to be a moderation bot so there should be a mod log channel for logs. Removing labels and closing.

**Comment by TrueWinter** [comment]
Re-opening this issue as I may want to make a public version of the bot soon and this will become a problem when I do.

**Comment by ghost** [comment]
Can be fixed easy i can do it if you can't right now

**Comment by TrueWinter** [comment]
@donkeymonkey1 Can you please see if you could fix this? I have just finished writing exams a few days ago and have not had time to finish setting up my new laptop for development.

**Comment by ghost** [comment]
@NdT3Development Will try to do no problems

**Comment by ChineseMarc** [comment]
I will fix this (i don't have internet home now but soon i should have it

**Comment by ChineseMarc** [comment]
@NdT3Development
I will get internet today and fix this.

**Comment by ChineseMarc** [comment]
@NdT3Development fixed it in #30

**Comment by TrueWinter** [comment]
I saw the pull request (I get a notification on Discord when something happens here). Snyk had an issue it seems and couldn't check for issues/vulnerabilities so I'm going to have to merge this later in the week.

**Comment by ethamitc** [comment]
Legit you just add a check to see if the channel exists and if it doesn't ignore the log message send.

**Comment by TrueWinter** [comment]
Yeah, a fix has been added in a pull request but there was a problem with some checks so ~~I can't merge it at this time.~~ Merged it.
