### ISSUE TITLE
Stats page

### ISSUE THREAD

**Issue by ghost** [NdT3Development/DiscordBot#25]
TypeError: moment.duration(...).format is not a function
[Hmm``](https://github.com/moment/moment/issues/1048)

**Comment by TrueWinter** [comment]
Not sure why this isn't working as it should. It used to work. I have added something that I think should fix the issue. 
Unfortunately, I cannot test the fix right now as my new laptop isn't set up for this yet and might not be set up for this until the end of June due to school work and exams.

**Comment by ghost** [comment]
Will test for you when i go home.

**Comment by ghost** [comment]
Fixed
Closing issue
