### ISSUE TITLE
How i host that in Glitch.com

### ISSUE THREAD

**Issue by jurgenjacobsen** [NdT3Development/DiscordBot#26]

**Comment by ghost** [comment]
I can help @Gugui000 
Add me Chinese_Marc#5516

**Comment by ghost** [comment]
`		domain: '${process.env.PROJECT_DOMAIN}.glitch.me', // Domain name (with port if not running behind proxy running on port 80). Example: 'domain': 'dashboard.bot-website.com' OR 'domain': 'localhost:33445'
		port: '3000', // The port that it should run on`
and for callback url use appname.glitch.me/callback
Replace domain and port with this if u need more help add me on discord Chinese_Marc#5516
