### ISSUE TITLE
Bot leaves voise channel just after playing music

### ISSUE THREAD

**Issue by DjDeveloperr** [NdT3Development/DiscordBot#31]
why?

**Comment by TrueWinter** [comment]
This is not a bug. It is intended behaviour for the bot to leave the voice channel and delete the music queue object after the queue has finished.

**Comment by DjDeveloperr** [comment]
what to do then?

**Comment by TrueWinter** [comment]
To ensure that the bot does not leave the voice channel after a song plays, add more songs to the queue.
