### ISSUE TITLE
Uncaught Exception:  TypeError:  Cannot read property 'has' of undefined

### ISSUE THREAD

**Issue by audiodk** [NdT3Development/DiscordBot#36]
I was wondering if you could help me fix this problem.  

`Uncaught Exception:  TypeError: Cannot read property 'has' of undefined`

it's happening in the message.js file in the events folder with this:

`if (client.talkedRecently.has(message.author.id)) {
			return message.reply(`You need to wait ${parseInt(guildSettings.commandTimeout)}ms seconds between each command`);
		}`

**Comment by TrueWinter** [comment]
I have just tested that functionality of the bot on a new setup and it is working fine.
I have had to add a config option (I forgot to add it) to the configuration file so you will need to run the following command to add the setting to all servers the bot is in:
```js
[prefix]eval client.guilds.forEach((g)=>{var s=client.settings.get(message.guild.id);s['commandTimeout']='2500';client.settings.set(g.id,s)});
```
Can you please send more information such as the Node.js version you are using and if you have changed any dependencies of the bot?

**Comment by audiodk** [comment]
sure.

I am using:
Node: v8.15.0
Discord.js: v11.4.2

I haven't changed anything at all for dependencies

**Comment by audiodk** [comment]
and I get that error as soon as I run any command.

**Comment by audiodk** [comment]
I don't know what I did but it's working fine now.  thank you for the help.

**Comment by TrueWinter** [comment]
Ok. Thank you for opening an issue. This issue actually made me discover a few new bugs in the bot.
If there is any more issues, feel free to open an issue here on GitHub, send me an email, or DM me on Discord.

**Comment by audiodk** [comment]
Ok I will.  I think it had something to do with the Discord.js version.  I uninstalled 11.4 and installed 11.2 and seemed to fix it.
