### ISSUE TITLE
Getting an error for the `reason` command

### ISSUE THREAD

**Issue by DieselJS** [NdT3Development/DiscordBot#40]
When I ban/Unban someone, It tells me to use the reason command.
I use `!reason 2 Test` for example and it says: 
`TypeError: Cannot read property '0' of undefined`
Around the 
```
        modLog.fetchMessages(caseLog.id).then(logMsg => {
            const embed = logMsg.embeds[0];
            embedSan(embed);
```
section
If anyone could help me get this working I'll be super delighted!
Thanks, DieselJS

**Comment by TrueWinter** [comment]
Do you have the mod log channel set in the server config (use the set command)?

**Comment by TrueWinter** [comment]
Closing this issue due to no reply.

**Comment by DieselJS** [comment]
Yes I did btw.

**Comment by DieselJS** [comment]
Yea I used the dashboard, default config, set command. Still doesn't work, console shows no error but the bot replies with "Unable to find that case number", which is about line 10-25.
