### ISSUE TITLE
Prefix not working

### ISSUE THREAD

**Issue by DNDCoding** [NdT3Development/DiscordBot#49]
I changed the default prefix in config.json from &&& to ! and after i run command !help, i get nothing but when i run &&&help, the command comes, any fix?

**Comment by NdT3Development** [comment]
The default config only affects new servers.

To update the prefix in an existing server, run `[prefix]set edit prefix [prefix]` where the first `[prefix]` is the current server prefix, and the second one is the new prefix.

**Comment by DNDCoding** [comment]
I already figured that out, but is there any way to set ! prefix as the default in all servers?

**Comment by NdT3Development** [comment]
Yes. Run the following command (only run it in one server):
`[prefix]eval client.guilds.forEach((g)=>{var s=client.settings.get(g.id);s.prefix='!';client.settings.set(g.id,s);});`

This will update the prefix to `!` in all servers the bot is in. New servers will take the prefix from default settings in the config file.
