### ISSUE TITLE
Invalid OAuth2 redirect_uri

### ISSUE THREAD

**Issue by Mairon31** [NdT3Development/DiscordBot#51]
Nothing changed from the dashboard.js file, and my config.js looks like this:

protect: "true"
domain: "dull-tern.glitch.me"

My Auth Url https://discordapp.com/oauth2/authorize?response_type=code&redirect_uri=https%3A%2F%2Fdull-term.glitch.me%2Fcallback&scope=identify%20guilds&client_id=659872929533657108

**Comment by TrueWinter** [comment]
Sorry for the late reply. I've been really busy.

Can you please log into the Discord developer dashboard (https://discordapp.com/developers/applications) and show me what you have set for the redirect URL?

**Comment by TrueWinter** [comment]
Closing this issue due to no reply.

**Comment by Mairon31** [comment]
Waitttt

**Comment by TrueWinter** [comment]
If you are still experiencing the issue, and can provide the requested information, I'll help you fix it.
